FROM python:3.11.5 as python
ENV PYTHONUNBUFFERED=true
RUN apt-get update -y && apt-get install -y python3-dev build-essential curl
WORKDIR /app


FROM python as poetry
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 -
COPY pyproject.toml ./
COPY poetry.lock ./
RUN poetry install --only main --no-interaction --no-ansi -vvv



FROM python as runtime
ENV PATH="/app/.venv/bin:$PATH"
COPY --from=poetry /app /app
COPY . /app/
EXPOSE 8000
ENV PYTHONPATH="${PYTHONPATH}:/app"
CMD ["python", "spartid_ais/aisapp.py"]
