services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: spartid-ais-web:latest
    ports:
      - "9101:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/spartid_ais
    env_file:
      - path: .spartid-ais.env
        required: false
    depends_on:
      - poller
      - db
    command: ["flask", "--app=spartid_ais", "run", "--host=0.0.0.0"]

  poller:
    restart: always
    image: spartid-ais-web:latest
    volumes:
      - database:/data/sqlite
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/spartid_ais
    depends_on:
      - db
    command: ["python", "spartid_ais/kystverket.py"]

  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spartid_ais
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  database:
