[tool.poetry]
name = "spartid-ais"
version = "0.1.0"
description = "AIS example with data from Kystverket in Norway"
authors = ["Knut H Pederseen <knuthp@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.2.2"
libais = "^0.17"
requests = "^2.28.1"
flask-sqlalchemy = "^3.0.2"
flask-marshmallow = "^0.14.0"



[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
flake8 = "^6.0.0"
isort = "^5.10.1"
black = "^22.6.0"


[tool.poetry.group.datasciene.dependencies]
pandas = "^1.4.4"
jupyterlab = "^3.4.5"
pyarrow = "^10.0.1"


[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
