"""Initial migration.

Revision ID: 18b677545b2f
Revises:
Create Date: 2023-10-08 16:25:53.032303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18b677545b2f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historic_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mmsi", sa.Integer(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_historic_position_mmsi"), ["mmsi"], unique=False
        )

    op.create_table(
        "imo_vessel_codes",
        sa.Column("mmsi", sa.Integer(), nullable=False),
        sa.Column("imo", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("flag", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("mmsi"),
    )
    with op.batch_alter_table("imo_vessel_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_imo_vessel_codes_mmsi"), ["mmsi"], unique=True
        )

    op.create_table(
        "last_position",
        sa.Column("mmsi", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("course", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("mmsi"),
    )
    with op.batch_alter_table("last_position", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_last_position_mmsi"), ["mmsi"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "HistoricPosition",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("mmsi", sa.INTEGER(), nullable=True),
        sa.Column("lat", sa.FLOAT(), nullable=True),
        sa.Column("long", sa.FLOAT(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("HistoricPosition", schema=None) as batch_op:
        batch_op.create_index("ix_HistoricPosition_mmsi", ["mmsi"], unique=False)

    op.create_table(
        "LastPosition",
        sa.Column("mmsi", sa.INTEGER(), nullable=False),
        sa.Column("lat", sa.FLOAT(), nullable=True),
        sa.Column("long", sa.FLOAT(), nullable=True),
        sa.Column("speed", sa.FLOAT(), nullable=True),
        sa.Column("course", sa.FLOAT(), nullable=True),
        sa.Column("heading", sa.FLOAT(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("mmsi"),
    )
    with op.batch_alter_table("LastPosition", schema=None) as batch_op:
        batch_op.create_index("ix_LastPosition_mmsi", ["mmsi"], unique=False)

    op.create_table(
        "ImoVesselCodes",
        sa.Column("mmsi", sa.VARCHAR(), nullable=False),
        sa.Column("imo", sa.VARCHAR(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("flag", sa.VARCHAR(), nullable=True),
        sa.Column("type", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("mmsi"),
    )
    with op.batch_alter_table("ImoVesselCodes", schema=None) as batch_op:
        batch_op.create_index("ix_ImoVesselCodes_mmsi", ["mmsi"], unique=False)

    with op.batch_alter_table("last_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_last_position_mmsi"))

    op.drop_table("last_position")
    with op.batch_alter_table("imo_vessel_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_imo_vessel_codes_mmsi"))

    op.drop_table("imo_vessel_codes")
    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historic_position_mmsi"))

    op.drop_table("historic_position")
    # ### end Alembic commands ###
