"""mapped

Revision ID: 2a973f6c71ca
Revises: cc5ba7461470
Create Date: 2023-10-11 23:04:05.152807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a973f6c71ca"
down_revision = "cc5ba7461470"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.alter_column("msg_type", existing_type=sa.SMALLINT(), nullable=False)
        batch_op.alter_column("repeat", existing_type=sa.SMALLINT(), nullable=False)
        batch_op.alter_column("mmsi", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=26), nullable=False
        )
        batch_op.alter_column("turn", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("speed", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("accuracy", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("lat", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("long", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("course", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("heading", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "maneuver", existing_type=sa.VARCHAR(length=17), nullable=False
        )
        batch_op.alter_column("raim", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("radio", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("imo_vessel_codes", schema=None) as batch_op:
        batch_op.alter_column("imo", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("flag", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("type", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("last_position", schema=None) as batch_op:
        batch_op.alter_column("lat", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("long", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("speed", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("course", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("heading", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("last_position", schema=None) as batch_op:
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("heading", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("course", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("speed", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("long", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("lat", existing_type=sa.FLOAT(), nullable=True)

    with op.batch_alter_table("imo_vessel_codes", schema=None) as batch_op:
        batch_op.alter_column("type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("flag", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("imo", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("radio", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("raim", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "maneuver", existing_type=sa.VARCHAR(length=17), nullable=True
        )
        batch_op.alter_column("heading", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("course", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("long", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("lat", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("accuracy", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("speed", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("turn", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=26), nullable=True
        )
        batch_op.alter_column("mmsi", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("repeat", existing_type=sa.SMALLINT(), nullable=True)
        batch_op.alter_column("msg_type", existing_type=sa.SMALLINT(), nullable=True)

    # ### end Alembic commands ###
