"""Extend historic_pos

Revision ID: cc5ba7461470
Revises: 18b677545b2f
Create Date: 2023-10-11 21:36:23.855055

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc5ba7461470"
down_revision = "18b677545b2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.add_column(sa.Column("msg_type", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("repeat", sa.SmallInteger(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "UnderWayUsingEngine",
                    "AtAnchor",
                    "NotUnderCommand",
                    "RestrictedManoeuverability",
                    "ConstrainedByHerDraught",
                    "Moored",
                    "Aground",
                    "EngagedInFishing",
                    "UnderWaySailing",
                    "AISSARTActive",
                    "Undefined",
                    name="navigationstatus",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("turn", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("speed", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("accuracy", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("course", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("heading", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "maneuver",
                sa.Enum(
                    "NotAvailable",
                    "NoSpecialManeuver",
                    "SpecialManeuver",
                    "UNDEFINED",
                    name="maneuverindicator",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("raim", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("radio", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historic_position", schema=None) as batch_op:
        batch_op.drop_column("radio")
        batch_op.drop_column("raim")
        batch_op.drop_column("maneuver")
        batch_op.drop_column("heading")
        batch_op.drop_column("course")
        batch_op.drop_column("accuracy")
        batch_op.drop_column("speed")
        batch_op.drop_column("turn")
        batch_op.drop_column("status")
        batch_op.drop_column("repeat")
        batch_op.drop_column("msg_type")

    # ### end Alembic commands ###
